### PR TITLE
[RPC Gateway] Increase Celo to 10% on RPC Gateway

### PR DESCRIPTION
**Pull request by rollingtumbling**

### CODE REVIEW

**Comment by rollingtumbling** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/Uniswap/routing-api/541?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#541** <a href="https://app.graphite.dev/github/pr/Uniswap/routing-api/541?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#539** <a href="https://app.graphite.dev/github/pr/Uniswap/routing-api/539?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#538** <a href="https://app.graphite.dev/github/pr/Uniswap/routing-api/538?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @rollingtumbling and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by cgkol** [comment]
Is there a description/ document where we can see the metrics and confirm everything looks as expected?

**Review by jsy1218 — APPROVED** [review]

**Comment by rollingtumbling** [comment]
### Merge activity

* **Apr 1, 6:39 PM EDT**: @rollingtumbling merged this pull request with [Graphite](https://app.graphite.dev/github/pr/Uniswap/routing-api/541).

**Comment by rollingtumbling** [comment]
> Is there a description/ document where we can see the metrics and confirm everything looks as expected?

https://docs.google.com/document/d/1jaKlScQVF20stprKA55_JK1fHmZTmZ-qIal1E8EDIpc/edit

**Pull request merged**
