### PR TITLE
prettier linter

### PR DESCRIPTION
**Pull request by ewilz**
When I run the linter this is the results I get. If this matches up with what you get @willpote or @snreynolds, maybe we want to merge this. Not sure if I'm all configured right.

also, I'd maybe want to add a hook here to run the linter automatically after a commit and write if updates are needed, similar to the other repos.

### CODE REVIEW

**Comment by willpote** [comment]
Thanks for doing this!

So what we use in the interface/sdk is:

```
"prettier": {
    "printWidth": 120,
    "semi": false,
    "singleQuote": true
  }
```

so we should probably use this config. Rip semi colons

**Comment by willpote** [comment]
Also yes if you can set up the hook that would be great! Have been meaning to do it but haven't had time

**Comment by ewilz** [comment]
RIP git blame. 

ready for  review @willpote

**Review by willpote — APPROVED** [review]
Cheers!

**Pull request merged**
