### PR TITLE
fix: hardcode gas on celo

### PR DESCRIPTION
**Pull request by jsy1218**
the gas used proprietary SOR algorithm is too low on celo, but tenderly cannot simulate on celo yet to support accurate gas estimate. mobile launch on celo requires a gas used, that will not result in mass onchain swap failure. We determined that routing-api returns a hardcoded 5 million gas used on celo would avoid large onchain swap failures on mobile.

tested locally with uniswap-web source, gas estimate doesn't change: https://app.warp.dev/block/iYh1m8qV3oW917Xa0W9knf
tested locally with uniswap-ios source, gas estimate changed to 5000000: https://app.warp.dev/block/Tjl6BiNxcK1vkr1yDfhARc

### CODE REVIEW

**Comment by jsy1218** [comment]
* **#760** <a href="https://app.graphite.dev/github/pr/Uniswap/routing-api/760?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @jsy1218 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by cgkol — COMMENTED** [review]
Can we pelase add a test here? This is similar to zksync right?

**Comment by jsy1218** [comment]
> Can we pelase add a test here? This is similar to zksync right?
> 
> 

yes, and also requested by mobile team

**Comment by jsy1218** [comment]
@cgkol added unit test

**Review by cgkol — APPROVED** [review]
TY friend

**Comment by jsy1218** [comment]
### Merge activity

* **Jun 25, 10:46 PM EDT**: @jsy1218 started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/Uniswap/routing-api/760).

**Pull request merged**
