### PR TITLE
chore: bump sor to 3.46.0 - feat: implement best swap route with v4 routes

### PR DESCRIPTION
**Pull request by jsy1218**
Release https://github.com/Uniswap/smart-order-router/pull/682

### CODE REVIEW

**Comment by jsy1218** [comment]
* **#822** <a href="https://app.graphite.dev/github/pr/Uniswap/routing-api/822?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @jsy1218 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by xrsv** [comment]
seems bump change is not included in PR

**Comment by jsy1218** [comment]
> seems bump change is not included in PR

yea, I'm integrating to see if I need to make more changes in SOR. turns out I missed a slight piece in SOR, will send in SOR first.

**Review by xrsv — APPROVED** [review]

**Comment by jsy1218** [comment]
### Merge activity

* **Aug 29, 2:39 PM EDT**: @jsy1218 started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/Uniswap/routing-api/822).

**Pull request merged**
