### PR TITLE
[RPC Gateway] Launch to 1% traffic of Avalanche

### PR DESCRIPTION
**Pull request by rollingtumbling**
Verified on local dev.

### CODE REVIEW

**Comment by rollingtumbling** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/Uniswap/routing-api/539?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#539** <a href="https://app.graphite.dev/github/pr/Uniswap/routing-api/539?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#538** <a href="https://app.graphite.dev/github/pr/Uniswap/routing-api/538?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @rollingtumbling and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by cgkol — APPROVED** [review]
Make sure the current one in prod is the same

**Review by jsy1218 — COMMENTED** [review]
What do you think about gradually launching celo to 100% first? I see we have better chance to trigger rpc failover when we have a single provider having larger percentage, rather than multiple providers with small percent.

**Comment by rollingtumbling** [comment]
> What do you think about gradually launching celo to 100% first? I see we have better chance to trigger rpc failover when we have a single provider having larger percentage, rather than multiple providers with small percent.

I do have that planned (will be in a separate PR). However after the last incident I think I want to minimize the risk and increase the success of deployment.

**Pull request merged**
