### PR TITLE
Bump SOR to 3.11.5

### PR DESCRIPTION
**Pull request by mikeki**
This version of SOR implements some changes with how we resolve tokens that were previously impossible to resolve (due to symbol returning bytes32 instead of string)

### CODE REVIEW

**Review by cgkol — APPROVED** [review]
did we test locally that this wont break it?

**Comment by jsy1218** [comment]
> did we test locally that this wont break it?

My understanding is that the E2E changes like this (routing-api & smart-order-route (including ABI) & contracts) are hard to get canary tested. Testing in local won't catch this regression, because it involves routing-api & smart-order-route calling the smart contracts via the ABI with particular token pairs, and we only have basic integ tests in our routing-api test suite. @mikeki Feel free to correct me.

**Review by jsy1218 — APPROVED** [review]

**Comment by mikeki** [comment]
I did a test on SOR and the test passed, so at least when it comes to tests this is looking good

**Comment by cgkol** [comment]
> > did we test locally that this wont break it?
> 
> My understanding is that the E2E changes like this (routing-api & smart-order-route (including ABI) & contracts) are hard to get canary tested. Testing in local won't catch this regression, because it involves routing-api & smart-order-route calling the smart contracts via the ABI with particular token pairs, and we only have basic integ tests in our routing-api test suite. @mikeki Feel free to correct me.

fwiw, @mikeki @jsy1218, siyu and I talked on Slack, and what I meant was that we could do this on our personal account to test the FE flow. maybe an overkill, but if its already presetup we can check some normal flows for quoting to make sure nothing breaks. Again, might be an overkill for this PR but does not hurt to test when we bump this in general, regardless of how big the change is

**Pull request merged**
